#POST http://localhost:8000/api/v1/eval/mobilepf/latest
POST http://localhost:8000/api/v1/eval/jamie-menu-64623317-d00c-4508-8db3-613d1ed24638/
Content-Type: application/json
X-API-Key: abc123

{
    "idade":13
}