name: Go

on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.16', '1.17', 'latest']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}

    - name: "Fetch dependencies"
      run: >
          go mod download
          export GO111MODULE=on
            
      # Only run gofmt, vet & lint against the latest Go version
    - name: "Run golint"
      run: >
          if [[ ${{ matrix.go_version }} = "latest" ]]; then
            go get -u golang.org/x/lint/golint
            golint ./...
          fi
          
    - name: "Run gofmt"
      run: >
          if [[ ${{ matrix.go_version }} = "latest" ]]; then
            diff -u <(echo -n) <(gofmt -d -e .)
          fi

    - name: "Run go vet"
      run: >
          if [[ ${{ matrix.go_version }} = "latest" ]]; then
            go vet -v ./...
          fi

    - name: Build
      run: go build -v ./...

    #- name: Test
    #  run: go test -v ./...
