name: Go

on:
  push:
    branches: all
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.16', '1.17']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build
      run: go build -v ./...

    #- name: Test
    #  run: go test -v ./...
